### ISSUE TITLE
Scope Creep

### ISSUE THREAD

**Issue by dahlbyk** [arex388/Arex388.AspNet.Mvc.Startup#1]
As I imagine thousands of projects will be over the coming years, I'm embarking upon an incremental migration of a classic ASP.NET MVC/WebAPI project to ASP.NET Core. I stumbled on this project via https://gist.github.com/davidfowl/563a602936426a18f67cd77088574e61, in search of scoped dependency support for my naïve implementation of `IDependencyResolver` for `Microsoft.Extensions.DependencyInjection`.

I stopped by to check if you'd be interested in expanding the scope of this project a bit to make migration easier in more scenarios, e.g.

- Automatically register a scoped [`IHttpContextAccessor`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.ihttpcontextaccessor)
- Automatically register a scoped `IOwinContext`
- Decouple the base project (Arex388.AspNet.Startup?) from MVC
- Add a separate WebApi `IDependencyResolver`, maybe with some attempt to align with https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.WebApiCompatShim ([GitHub](https://github.com/dotnet/aspnetcore/tree/29a25b2ed14b8c81f8ae9b356e171afd77f99f44/src/Microsoft.AspNet.Mvc.WebApiCompatShim))?
- As @davidfowl suggested, "it might be interesting to go further and look at what it means to run the generic host in a classic ASP.NET application as well. That way you get configuration, logging and DI."
  - `IConfiguration` from Web.config? https://benfoster.io/blog/net-core-configuration-legacy-projects/
- There are also some common System.Web integration points that I've started replacing with implementations of `Microsoft.AspNetCore` equivalents (e.g. a model binder for [`IFormFile`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.iformfile) instead of `HttpPostedFileBase`)

Ultimately my goal is an in-place migration instead of side-by-side, and I'm interested in helping ease that pain for others while I'm at it. If you're at all interested, I'd be glad to help. If you're not, I'd love to use what you have so far as a starting point. (This project does not currently have an license.)

**Comment by arex388** [comment]
Hey @dahlbyk, sorry for the delayed reply. I'm open to any suggestions you have to make this project more versatile and helpful to other developers in the same boat you and I are in. Unfortunately, I work two full time jobs and my time to contribute is very limited... As for the licensing, I never really understood what license to pick so I just left it blank.

On a side note, I'm curious how you plan to do your in-place conversion? My app implements vertical slices, so I was planning on separating those out into a standalone library, and then have the existing .NET Framework app and a new .NET Core app to switch to later on. Haven't gotten that for yet though...

By the way, what was the conclusion to the Hangfire issue you opened? I read through it and saw that you closed it, but I wasn't clear on what the conclusion was, or I missed it.

Thanks for offering to contribute by the way!

**Comment by dahlbyk** [comment]
> Hey @dahlbyk, sorry for the delayed reply.

Never apologize for "delays" on free work. 😀 

> I'm open to any suggestions you have to make this project more versatile and helpful to other developers in the same boat you and I are in. Unfortunately, I work two full time jobs and my time to contribute is very limited...

Understood. You deserve credit for getting this started, but if your circumstances don't lend to taking the lead that's fine. To that end, I might make an Organization to host whatever this project turns into? Thoughts on a name other than yours?

> As for the licensing, I never really understood what license to pick so I just left it blank.

I'm not a lawyer, let alone your lawyer, so don't consider this legal advice, but https://choosealicense.com/ does a good job of describing your options. I personally use MIT, as does .NET Core; ASP.NET uses Apache. A reciprocal license like GPL might discourage folks from using the project.

> On a side note, I'm curious how you plan to do your in-place conversion? My app implements vertical slices, so I was planning on separating those out into a standalone library, and then have the existing .NET Framework app and a new .NET Core app to switch to later on. Haven't gotten that for yet though...

I'm still working on exactly what the plan is there. For now I've converted the project in-place in a separate [git worktree](https://git-scm.com/docs/git-worktree) and am chipping away at the build errors I encounter.

> By the way, what was the conclusion to the Hangfire issue you opened? I read through it and saw that you closed it, but I wasn't clear on what the conclusion was, or I missed it.

If you take a dependency on [Hangfire.NetCore](https://www.nuget.org/packages/Hangfire.NetCore) instead of [Hangfire.AspNetCore](https://www.nuget.org/packages/Hangfire.AspNetCore) you can avoid extra dependencies beyond the Microsoft abstractions.

> Thanks for offering to contribute by the way!

A blessing and a curse. 😎

**Comment by davidfowl** [comment]
I'll happily lend my expertise. Let me know if you need advice or a code review

**Comment by dahlbyk** [comment]
> I'll happily lend my expertise. Let me know if you need advice or a code review

Appreciate that, @davidfowl. Would you mind expanding a bit on:
> it might be interesting to go further and look at what it means to run the generic host in a classic ASP.NET application as well. That way you get configuration, logging and DI.

I see a few different layers of abstractions, but I'm not sure what you mean by "run the generic host":

- [Microsoft.AspNetCore.Hosting.Abstractions](https://www.nuget.org/packages/Microsoft.AspNetCore.Hosting.Abstractions/) ([src](https://github.com/dotnet/aspnetcore/tree/master/src/Hosting/Abstractions/src))
  - `IStartup`, `IWebHostEnvironment`, `IWebHostBuilder`
  - [Microsoft.Extensions.Hosting.Abstractions](https://www.nuget.org/packages/Microsoft.Extensions.Hosting.Abstractions/) ([src](https://github.com/dotnet/runtime/tree/master/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src))
    - Configuration, DependencyInjection, FileProviders, Logging
  - [Microsoft.AspNetCore.Http.Abstractions](https://www.nuget.org/packages/Microsoft.AspNetCore.Http.Abstractions/) ([src](https://github.com/dotnet/aspnetcore/tree/master/src/Http/Http.Abstractions/src))
    - `IApplicationBuilder`, `HttpContext`, `HttpRequest`, `HttpResponse`
    - [Microsoft.AspNetCore.Http.Features](https://www.nuget.org/packages/Microsoft.AspNetCore.Http.Features/) ([src](https://github.com/dotnet/aspnetcore/tree/master/src/Http/Http.Features/src))
      - Fuzzy on what "Features" means internally, but `IFormFile` and `ISession` here seem useful?
  - [Microsoft.AspNetCore.Hosting.Server.Abstractions](https://www.nuget.org/packages/Microsoft.AspNetCore.Hosting.Server.Abstractions/) ([src](https://github.com/dotnet/aspnetcore/tree/master/src/Hosting/Server.Abstractions/src))
    - `IServer`, `IHttpApplication`

**Comment by dahlbyk** [comment]
> I see a few different layers of abstractions, but I'm not sure what you mean by "run the generic host":

I suppose you might literally mean run [`GenericHost`](https://github.com/dotnet/aspnetcore/tree/f54b590804ecacc328d9050ee1bdbaede9fb57a1/src/Hosting/Hosting/src/GenericHost) from [Microsoft.AspNetCore.Hosting](https://www.nuget.org/packages/Microsoft.AspNetCore.Hosting), which depends on [Microsoft.AspNetCore.Http](https://www.nuget.org/packages/Microsoft.AspNetCore.Http/) ([src](https://github.com/dotnet/aspnetcore/tree/master/src/Http/Http/src)). 🤔

**Comment by davidfowl** [comment]
I think it depends on what the goal is. I think its possible to adopt `Microsoft.Extensions.Hosting.Abstractions` and the DI container (ConfigureServices). You could also make `IWebHostEnvironment` work but I'm not sure about adapting the Http* layer.

**Comment by dahlbyk** [comment]
I semi-forked this as https://github.com/dahlbyk/Unravel:

> [Unravel.Startup](https://github.com/dahlbyk/Unravel/blob/main/src/Startup/README.md) ([NuGet](https://www.nuget.org/packages/Unravel.Startup)) provides a fully configurable ASP.NET Core IWebHost on top of System.Web via OWIN, with forward-compatible dependency injection, configuration and logging.

**Comment by arex388** [comment]
@dahlbyk that's really cool, and quite a hefty undertaking! You're going to be busy... 😅
