### ISSUE TITLE
Supported Dependency Versions

### ISSUE THREAD

**Issue by dahlbyk** [arex388/Arex388.AspNet.Mvc.Startup#5]
I just noticed 3c50811ae71c7ae419dcd60584f1a54d6e1a0437 bumped to `Microsoft.Extensions.DependencyInjection@5`:
https://github.com/arex388/Arex388.AspNet.Mvc.Startup/blob/6b6b160192414b56f5c8d355325cd70d711098d6/Arex388.AspNet.Mvc.Startup.csproj#L24-L25

Since we're targeting .NET Framework, I recommend limiting to [supported dependency versions](https://dotnet.microsoft.com/platform/support/policy/aspnetcore-2.1), i.e. [2.1.1](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection/2.1.1).

- [.NET Official Support Policy](https://dotnet.microsoft.com/platform/support/policy#dotnet-framework)
  > ### .NET Framework
  > Support for .NET Framework follows the Lifecycle Policy of the parent Windows operating system.
- [ASP.NET Support Policy](https://dotnet.microsoft.com/platform/support/policy/aspnet#dotnet-core)
  > To help facilitate migrating applications to ASP.NET Core on .NET Core, the following ASP.NET Core 2.1 (latest patched version only) [packages](https://dotnet.microsoft.com/platform/support/policy/aspnetcore-2.1) will be supported on the .NET Framework and follow the support cycle for those .NET Framework versions.

**Comment by arex388** [comment]
So, I don't really consider this to be an issue because:

- The linked article was written probably in the 2.1 timeline and was never updated since.
- v2.1.1 supports .NET Framework 4.6.1+, as do all other version above it up to the current v5.0.2.
- This library targets .NET Framework 4.6.1+ so I don't see any conflicts if `Microsoft.Extensions.DependencyInjection` also supports it.
- In my ASP.NET MVC project targeting .NET Framework 4.8 it's all working just fine.

**Comment by dahlbyk** [comment]
> * The linked article was written probably in the 2.1 timeline and was never updated since.

While these libraries _work_ on newer versions, **official support** for running ASP.NET Core and its dependencies **on .NET Framework** is limited to 2.1.x. **Update:** added additional Official Support links to the issue Description.

An app that depends on this project can always install a newer version of the various dependencies, if they don't care about support, and apply binding redirects to make everything happy. I just thought since this project is explicitly about running on Framework that maintaining explicit alignment with official support might find more users.

**Comment by arex388** [comment]
Fair enough. For v1.0.6 I've reverted it back to use v2.1.1 and the binding redirects to 5.0.2 seem to be working fine in my project.
